### ISSUE TITLE
Make `DateOnly` and `TimeOnly` JSON convertes lax by default

### ISSUE THREAD

**Issue by jakubfijalkowski** [leancodepl/corelibrary#399]
After robustness principle. Plus, we are now not compatible with our contractsgenerator.

**Comment by Saancreed** [comment]
Now there's quite a few other things we can do here while working on this (cc: @Anonim0990)

What needs to be done here:

1. Remove base `JsonDateOnlyConverter` and `JsonTimeOnlyConverter` because .NET 7.0 handles them just fine.
2. Rework `JsonLaxDateOnlyConverter` to read into a stack-allocated span instead of heap-allocating strings.
3. Implement `WriteAsPropertyName` and `ReadAsPropertyName` in our converters if they don't work as dictionary keys like we'd want them to.
4. Add `JsonLaxTimeOnlyConverter` and `JsonLaxDateTimeOffsetConverter` which can handle at least _some_ of the nonsense we can receive from our clients (while applying guidelines from points 2 and 3).
5. Update converters in `RemoteCQRSMiddlewareExtensions.UseRemoteCQRS` to use our 3 lax ones by default.
