### ISSUE TITLE
Use IEventsExecutor or RequestEventsExecutor middleware to handle per-async requests

### ISSUE THREAD

**Issue by jmicho-alx** [leancodepl/corelibrary#546]
I'm getting `InvalidOperationException: Use IEventsExecutor or RequestEventsExecutor middleware to handle per-async requests` when running code that emits domain event in a test fixture that inherits from `LeanCodeTestFactory`. This only happens when multiple tests are run in parallel. The same code works correctly when executed through CQRS. 

```
  Message: 
System.InvalidOperationException : Use IEventsExecutor or RequestEventsExecutor middleware to handle per-async requests.

  Stack Trace: 
IDomainEventInterceptor.Intercept(IDomainEvent domainEvent)
DomainEvents.Raise[TEvent](TEvent domainEvent)
Subscription.Create(SId`1 companyID, SubscriptionPlanType planType, SubscriptionBillingPeriod billingPeriod, SubscriptionExpirationTime expirationTime) line 94
TopDealsLimitResetJobTests.CreateSubscription(SId`1 companyID, SubscriptionPlanType planType, SubscriptionBillingPeriod billingPeriod) line 159
TopDealsLimitResetJobTests.PrepareSUT(SubscriptionPlanType planType, SubscriptionBillingPeriod billingPeriod) line 137
TopDealsLimitResetJobTests.ShouldMonthlyResetTopDealsLimit(SubscriptionPlanType planType) line 68
```

The code uses EF repositories to inject entities to the system. Domain events raised in these methods are not received by consumers.

The code that should raises this exception is:
```c#
private async Task CreateSubscription(
    SId<Company> companyID,
    SubscriptionPlanType planType,
    SubscriptionBillingPeriod billingPeriod
)
{
    var subscription = Subscription.Create(companyID, planType, billingPeriod, SubscriptionExpirationTime.Never);
    await subscriptionsRepository.AddAsync(subscription);
}
```

Content of `Subscription.Create`:
```c#
public static Subscription Create(
    SId<Company> companyID,
    SubscriptionPlanType planType,
    SubscriptionBillingPeriod billingPeriod,
    SubscriptionExpirationTime expirationTime
)
{
    var id = SId<Subscription>.New();
    var subscription = new Subscription(companyID, planType, billingPeriod, expirationTime) { Id = id };

    DomainEvents.Raise(
        new SubscriptionCreatedEvent(id, companyID, planType, subscription.Plan, billingPeriod, expirationTime)
    );

    return subscription;
}
```

The event that goes missing:
```c#
public class SubscriptionCreatedEvent(
    SId<Subscription> subscriptionID,
    SId<Company> companyID,
    SubscriptionPlanType planType,
    SubscriptionPlan plan,
    SubscriptionBillingPeriod billingPeriod,
    SubscriptionExpirationTime expirationTime
) : IDomainEvent
{
    public Guid Id { get; } = Guid.NewGuid();
    public DateTime DateOccurred { get; } = TimeProvider.Now;
    public SId<Subscription> SubscriptionID { get; } = subscriptionID;
    public SId<Company> CompanyID { get; } = companyID;
    public SubscriptionPlanType PlanType { get; } = planType;
    public SubscriptionPlan Plan { get; } = plan;
    public SubscriptionBillingPeriod BillingPeriod { get; } = billingPeriod;
    public SubscriptionExpirationTime ExpirationTime { get; } = expirationTime;
}
```

CoreLibrary version: `7.0.1636`

**Comment by jakubfijalkowski** [comment]
Hey, thanks for reporting this. :)

From the looks, it seems that this

> This only happens when multiple tests are run in parallel.

is the culprit. `DomainEvents` is not really [thread safe](https://github.com/leancodepl/corelibrary/blob/v7.0/src/Domain/LeanCode.DomainModels/Model/DomainEvents.cs#L7-L10), thus it has some limitations to how it can be used. The main approach here is to keep a single _interceptor_ per process (either [MT-based one](https://github.com/leancodepl/corelibrary/blob/v7.0/src/Domain/LeanCode.DomainModels.MassTransitRelay/AsyncEventsInterceptor.cs) or [the one for tests](https://github.com/leancodepl/corelibrary/blob/v7.0/src/Testing/LeanCode.DomainModels.EventsExecution.TestHelpers/EventsInterceptor.cs) ). Switching them mid-run needs to be done with care, and most of the time it will not work either way because of races.

If the events work when run serially, then I would say that there is other code (other kind of tests in the same assembly?) that re-sets the interceptor. If that is not the case, then I would say that you either missed the [MT Module](https://github.com/leancodepl/corelibrary/blob/v7.0/src/Domain/LeanCode.DomainModels.MassTransitRelay/MassTransitRelayModule.cs) in the tests (or other kind of module that handles these events) or forgot to [Configure](https://github.com/leancodepl/corelibrary/blob/v7.0/src/Testing/LeanCode.DomainModels.EventsExecution.TestHelpers/EventsInterceptor.cs#L13) the test interceptor in this particular test.

**Comment by jmicho-alx** [comment]
Hmm, thanks for the clues, I'll check what might be the reason then. The real problem seems to be that, when the test runs on its own, the event is not being processed at all. Might it be connected to the outbox pattern implementation? What triggers the actual publishing of domain events?

**Comment by jakubfijalkowski** [comment]
The events are not published directly during the call to "Publish", but as you correctly pointed out, first go through outbox (are basically stored transactionally along the aggregates), unless you use the [PublishEvents](https://github.com/leancodepl/corelibrary/blob/v7.0/src/Domain/LeanCode.DomainModels.MassTransitRelay/Middleware/EventsPublisherElement.cs) extension. The outbox in v7 (it changed in v8) is optimized for the happy path, thus it tries to publish the message to MassTransit [as fast as it can](https://github.com/leancodepl/corelibrary/blob/v7.0/src/Domain/LeanCode.DomainModels.MassTransitRelay/EventsStore.cs#L33-L38). Thus, the event ends up on the bus quite quickly - when using in-memory bus, it should be almost immediate (and should not rely on database at all, although it will be saved there).

The problem is that "publish" does not mean that the consumers will run. In-memory bus in MT runs the consumers frequently, but not instantaneously. There will always be some minor delay between "publish" and run. Moreover, nothing waits for the consumers to run in tests, so after executing a command, the consumers might start running but the test will be already finished. If you depend on the side effects of events in tests, you have to wait for the processing using the [testing module](https://github.com/leancodepl/corelibrary/blob/v7.0/src/Domain/LeanCode.DomainModels.MassTransitRelay/Testing/MassTransitTestRelayModule.cs) and a helper method (it is available in v8, but not in v7 unfortunately):

```
// It should be a part of a class that derives from `LeanCodeTestFactory`
public async Task WaitForProcessingAsync()
{
    using var scope = Services.CreateScope();
    var monitor = scope.ServiceProvider.GetRequiredService<IBusActivityMonitor>();
    // Allow some processing time, selected arbitrarily
    var res = await monitor.AwaitBusInactivity(TimeSpan.FromSeconds(140));
    res.Should() // This one uses fluent assertions
        .BeTrue(because: "The service bus should finish processing in allowed time.");
}
```

**Comment by jmicho-alx** [comment]
> public async Task WaitForProcessingAsync()

We are actually using this pattern. It works when used along with CQRS, but not when the repositories are accessed directly, that's why I suspected something in the CQRS pipeline interacted with the outbox pattern.

**Comment by jakubfijalkowski** [comment]
Ah, missed the fact that you are not going through the CQRS pipeline but invoking code underneath yourself. In that case you are right - the MT module [registers AsyncEventInterceptor](https://github.com/leancodepl/corelibrary/blob/v7.0/src/Domain/LeanCode.DomainModels.MassTransitRelay/MassTransitRelayModule.cs#L51-L55) as a dependency with custom activation that sets the `DomainEvents.Interceptor` on first use (which is resolved for the first time along the CQRS pipeline).

You can use [SimpleEventsExecutor](https://github.com/leancodepl/corelibrary/blob/v7.0/src/Domain/LeanCode.DomainModels.MassTransitRelay/Simple/SimpleEventsExecutor.cs) to solve this (resolve it from the DI container and run your code as a lambda passed to `HandleEventsOfAsync`).

**Comment by jmicho-alx** [comment]
This worked, thanks. Turns out that the two problems, the internal exception and the missed event, can both be solved by using `SimpleEventsExecutor`.
